-- 1. Crear tabla de categorías de productos (si no existe)
CREATE TABLE IF NOT EXISTS product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar categorías base
INSERT INTO product_categories (name) VALUES
('Alimentos'),
('Bebidas'),
('Electrónica'),
('Ferretería'),
('Oficina'),
('Aseo'),
('Ropa'),
('Medicamentos'),
('Otros')
ON CONFLICT (name) DO NOTHING;

-- 2. Crear tabla de productos (si no existe)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL, -- Se puede mantener como texto o relacionar con FK, dejaremos texto por simplicidad actual
  unit_price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  min_stock NUMERIC DEFAULT 5,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Crear tabla de movimientos (si no existe)
CREATE TABLE IF NOT EXISTS movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  qty NUMERIC NOT NULL,
  type TEXT CHECK (type IN ('in', 'out')),
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Habilitar RLS (Row Level Security) para seguridad básica
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso (Permitir todo a usuarios autenticados para simplificar por ahora)
CREATE POLICY "Enable all access for authenticated users on products" ON products
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Enable all access for authenticated users on movements" ON movements
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for authenticated users on product_categories" ON product_categories
  FOR SELECT USING (auth.role() = 'authenticated');
