-- 20260622_s7_venta_conectada.sql
-- S7 (Q12 venta atómica + Q21 margen) — Venta conectada Finanzas↔Almacén (un producto).
-- ----------------------------------------------------------------------------
-- EXPAND · idempotente · aditivo (tabla + RPC nuevas; no toca datos existentes).
--  * sale_items: línea de venta (precio + COGS sellado → margen derivable). El cliente
--    SOLO lee (RLS select); la única vía de escritura es register_sale (SECURITY DEFINER).
--  * register_sale: en UNA transacción crea el ingreso, descuenta stock, inserta el
--    movimiento de salida (COGS = avg_cost, transaction_id) y la línea de venta. Si algo
--    falla (stock, límite mensual, cierre de período) → rollback total.
-- ----------------------------------------------------------------------------

create table if not exists public.sale_items (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default public.get_current_business_id(),
  transaction_id bigint not null references public.transactions(id) on delete cascade,
  product_id     bigint not null references public.products(id),
  qty            numeric not null check (qty > 0),
  unit_price     numeric not null check (unit_price >= 0),
  unit_cost      numeric not null default 0,
  created_at     timestamptz not null default now()
);
create index if not exists idx_sale_items_tx      on public.sale_items(transaction_id);
create index if not exists idx_sale_items_product on public.sale_items(product_id);

alter table public.sale_items enable row level security;

-- Solo lectura para el cliente (la escritura va por register_sale, que bypassa RLS).
drop policy if exists sale_items_read on public.sale_items;
create policy sale_items_read on public.sale_items
  for select using (public.has_permission_secure(user_id, 'finanzas.view'));

create or replace function public.register_sale(
  p_payload     jsonb,
  p_product_id  bigint,
  p_qty         numeric,
  p_unit_price  numeric
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_business  uuid := public.get_current_business_id();
  v_stock_old numeric;
  v_avg       numeric;
  v_currency  text;
  v_name      text;
  v_amount    numeric;
  v_status    text;
  v_paid      numeric;
  v_due       timestamptz;
  v_tx_id     bigint;
begin
  if v_business is null then
    raise exception 'No hay negocio en contexto' using errcode = '42501';
  end if;
  if p_qty is null or p_qty <= 0 then
    raise exception 'La cantidad debe ser mayor que 0' using errcode = '22023';
  end if;
  if p_unit_price is null or p_unit_price < 0 then
    raise exception 'El precio de venta no puede ser negativo' using errcode = '22023';
  end if;
  if not public.has_permission_secure(v_business, 'finanzas.create') then
    raise exception 'No autorizado: requiere permiso finanzas.create' using errcode = '42501';
  end if;
  if not public.has_permission_secure(v_business, 'warehouse.move') then
    raise exception 'No autorizado: requiere permiso warehouse.move' using errcode = '42501';
  end if;

  -- Producto del negocio bajo lock; valida stock ANTES de crear nada.
  select stock, avg_cost, currency, name into v_stock_old, v_avg, v_currency, v_name
  from public.products
  where id = p_product_id and user_id = v_business
  for update;
  if not found then
    raise exception 'Producto no encontrado en el negocio' using errcode = 'P0002';
  end if;
  if v_stock_old < p_qty then
    raise exception 'Stock insuficiente para la venta' using errcode = '23514';
  end if;

  -- Monto calculado server-side (no se confía del cliente). Moneda = la del producto.
  v_amount := p_qty * p_unit_price;

  v_status := coalesce(p_payload->>'status', 'paid');
  if v_status not in ('paid', 'pending', 'partial') then v_status := 'paid'; end if;
  v_paid := case when v_status = 'paid' then v_amount else 0 end;
  v_due  := case when v_status = 'paid' then null
                 else nullif(p_payload->>'due_date', '')::timestamptz end;

  -- 1) Ingreso (dispara saldo, límite mensual, cierre de período y auditoría).
  insert into public.transactions (
    user_id, date, amount, currency, category, description, type,
    contact_id, status, due_date, paid_amount, details
  ) values (
    v_business,
    coalesce(nullif(p_payload->>'date', '')::timestamptz, now()),
    v_amount,
    v_currency,
    coalesce(nullif(p_payload->>'category', ''), 'Ventas'),
    coalesce(nullif(p_payload->>'description', ''), 'Venta de ' || v_name),
    'income',
    nullif(p_payload->>'contact_id', '')::bigint,
    v_status,
    v_due,
    v_paid,
    jsonb_build_object('payment_method', p_payload->>'payment_method', 'sale', true)
  )
  returning id into v_tx_id;

  -- 2) Descontar stock + movimiento de salida con COGS sellado y transaction_id.
  update public.products
    set stock = stock - p_qty, updated_at = now()
    where id = p_product_id and user_id = v_business;

  insert into public.movements (product_id, qty, type, user_id, unit_cost, transaction_id, moved_at)
  values (p_product_id, p_qty, 'out', v_business, v_avg, v_tx_id, now());

  -- 3) Línea de venta: precio + COGS sellado → margen derivable (Q21).
  insert into public.sale_items (user_id, transaction_id, product_id, qty, unit_price, unit_cost)
  values (v_business, v_tx_id, p_product_id, p_qty, p_unit_price, v_avg);

  return jsonb_build_object(
    'transaction_id', v_tx_id,
    'amount',         v_amount,
    'currency',       v_currency,
    'cogs',           v_avg * p_qty,
    'margin',         (p_unit_price - v_avg) * p_qty,
    'new_stock',      v_stock_old - p_qty
  );
end;
$$;

revoke all on function public.register_sale(jsonb, bigint, numeric, numeric) from public;
grant execute on function public.register_sale(jsonb, bigint, numeric, numeric) to authenticated;

-- ----------------------------------------------------------------------------
-- ROLLBACK (manual):
--   drop function if exists public.register_sale(jsonb, bigint, numeric, numeric);
--   drop table if exists public.sale_items;
-- ----------------------------------------------------------------------------
