-- Dynamic Inventory Module (Areas, Fields, Items) with strict per-user isolation
-- 1) Areas definition
CREATE TABLE IF NOT EXISTS inventory_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  name TEXT NOT NULL,
  icon TEXT, -- lucide-react icon name (e.g., 'Warehouse', 'Bed', 'Lamp')
  slug TEXT, -- optional friendly path segment
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, slug)
);

-- 2) Area fields (dynamic form builder)
CREATE TABLE IF NOT EXISTS inventory_area_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  area_id BIGINT REFERENCES inventory_areas(id) ON DELETE CASCADE,
  name TEXT NOT NULL, -- machine name (key)
  label TEXT NOT NULL, -- human label
  type TEXT NOT NULL CHECK (type IN ('text','number','select','color','date','boolean','textarea')),
  required BOOLEAN DEFAULT FALSE,
  options JSONB, -- for 'select' or additional config (e.g., unit)
  "order" INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3) Items (values stored as JSONB to allow flexible schema)
CREATE TABLE IF NOT EXISTS inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  area_id BIGINT REFERENCES inventory_areas(id) ON DELETE CASCADE,
  values JSONB NOT NULL, -- { field_key: value }
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_inventory_areas_user_id ON inventory_areas(user_id);
CREATE INDEX IF NOT EXISTS idx_inventory_area_fields_user_id ON inventory_area_fields(user_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_user_id ON inventory_items(user_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_area ON inventory_items(area_id);

-- Enable Row Level Security
ALTER TABLE inventory_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_area_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;

-- Idempotent policies
-- Areas
DROP POLICY IF EXISTS "Areas: select own" ON inventory_areas;
DROP POLICY IF EXISTS "Areas: insert own" ON inventory_areas;
DROP POLICY IF EXISTS "Areas: update own" ON inventory_areas;
DROP POLICY IF EXISTS "Areas: delete own" ON inventory_areas;

CREATE POLICY "Areas: select own" ON inventory_areas
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Areas: insert own" ON inventory_areas
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Areas: update own" ON inventory_areas
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Areas: delete own" ON inventory_areas
  FOR DELETE USING (auth.uid() = user_id);

-- Area Fields
DROP POLICY IF EXISTS "Fields: select own" ON inventory_area_fields;
DROP POLICY IF EXISTS "Fields: insert own" ON inventory_area_fields;
DROP POLICY IF EXISTS "Fields: update own" ON inventory_area_fields;
DROP POLICY IF EXISTS "Fields: delete own" ON inventory_area_fields;

CREATE POLICY "Fields: select own" ON inventory_area_fields
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Fields: insert own" ON inventory_area_fields
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Fields: update own" ON inventory_area_fields
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Fields: delete own" ON inventory_area_fields
  FOR DELETE USING (auth.uid() = user_id);

-- Items
DROP POLICY IF EXISTS "Items: select own" ON inventory_items;
DROP POLICY IF EXISTS "Items: insert own" ON inventory_items;
DROP POLICY IF EXISTS "Items: update own" ON inventory_items;
DROP POLICY IF EXISTS "Items: delete own" ON inventory_items;

CREATE POLICY "Items: select own" ON inventory_items
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Items: insert own" ON inventory_items
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Items: update own" ON inventory_items
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Items: delete own" ON inventory_items
  FOR DELETE USING (auth.uid() = user_id);
