-- Fase 5: Tipos de cambio para consolidar multimoneda en la moneda principal.
-- Modelo: units_per_base = cuántas unidades de esta moneda equivalen a 1 unidad
-- de la moneda base (la principal). Ej. base=USD, CUP con units_per_base=420
-- significa "1 USD = 420 CUP". Conversión a base: monto / units_per_base.
-- Carga manual (tasas informales). La moneda base no necesita fila (rate=1).
create table if not exists public.exchange_rates (
  id bigint generated by default as identity primary key,
  user_id uuid not null default get_current_business_id() references auth.users(id),
  currency_code text not null references public.currencies(code),
  units_per_base numeric not null check (units_per_base > 0),
  effective_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, currency_code, effective_date)
);

create index if not exists exchange_rates_user_idx on public.exchange_rates(user_id);
create index if not exists exchange_rates_lookup_idx on public.exchange_rates(user_id, currency_code, effective_date desc);

alter table public.exchange_rates enable row level security;

-- RLS: lectura para quien ve finanzas (el dashboard consolida con estas tasas);
-- escritura para quien edita finanzas (la gestión vive en Configuración, owner-gated).
create policy exchange_rates_read on public.exchange_rates for select
  using (has_permission_secure(user_id, 'finanzas.view'));
create policy exchange_rates_insert on public.exchange_rates for insert
  with check ((user_id = get_current_business_id()) and has_permission_secure(user_id, 'finanzas.edit'));
create policy exchange_rates_update on public.exchange_rates for update
  using (has_permission_secure(user_id, 'finanzas.edit'))
  with check (has_permission_secure(user_id, 'finanzas.edit'));
create policy exchange_rates_delete on public.exchange_rates for delete
  using (has_permission_secure(user_id, 'finanzas.delete'));
