-- ============================================================================
-- PAGOS PREMIUM · FASE 1 — Cimientos de datos
-- (docs/PLAN_PAGOS_PREMIUM.md · Fase 1). Aplicado vía apply_migration.
--
-- Qué hace:
--  1) subscriptions.billing_cycle (monthly|quarterly|annual)
--  2) plans.pricing (jsonb) — fuente única de precios: Mensual $10 / Trimestral $30 / Anual $102 (-15%)
--  3) billing_config (1 fila): reminder_lead_days (7) y grace_days (3) — política global de avisos/gracia
--  4) payments — historial de pagos + RLS (lee owner/equipo/admin; escribe solo RPC admin)
--  5) get_effective_plan_state(business) → {plan_id,status,payment_state(ok|due_soon|grace|blocked|free),
--     current_period_end,grace_until,days_until_due,billing_cycle,lead_days,grace_days}
--  6) admin_record_payment(...) — registra pago + auditoría (solo admin)
--  7) helpers billing_cycle_months / premium_price_for_cycle
--  8) approve_plan_change_request y admin_set_business_plan: aceptan billing_cycle, fijan el período por
--     ciclo y CREAN una fila en payments al activar Premium (compatibles hacia atrás: 3/4 args siguen
--     funcionando porque el nuevo parámetro es opcional). DROP+CREATE para evitar overloads ambiguos.
--
-- Idempotente. NO convierte premium→free (eso es Fase 3). Sin cambios de UX.
-- Rollback resumido al final.
-- ============================================================================

-- 1) Ciclo de facturación en subscriptions -----------------------------------
ALTER TABLE public.subscriptions
  ADD COLUMN IF NOT EXISTS billing_cycle text NOT NULL DEFAULT 'monthly';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'subscriptions_billing_cycle_check'
  ) THEN
    ALTER TABLE public.subscriptions
      ADD CONSTRAINT subscriptions_billing_cycle_check
      CHECK (billing_cycle IN ('monthly','quarterly','annual'));
  END IF;
END $$;

-- 2) Precios por ciclo en plans (fuente única) -------------------------------
ALTER TABLE public.plans
  ADD COLUMN IF NOT EXISTS pricing jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.plans
SET pricing = jsonb_build_object(
  'monthly', 10,
  'quarterly', 30,
  'annual', 102,
  'annual_discount_pct', 15,
  'currency', 'USD'
)
WHERE id = 'premium';

UPDATE public.plans
SET pricing = jsonb_build_object('monthly', 0, 'quarterly', 0, 'annual', 0, 'currency', 'USD')
WHERE id = 'free';

-- 3) Config global de facturación (1 fila) -----------------------------------
CREATE TABLE IF NOT EXISTS public.billing_config (
  id smallint PRIMARY KEY DEFAULT 1,
  reminder_lead_days integer NOT NULL DEFAULT 7 CHECK (reminder_lead_days >= 0),
  grace_days integer NOT NULL DEFAULT 3 CHECK (grace_days >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT billing_config_singleton CHECK (id = 1)
);

INSERT INTO public.billing_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.billing_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS billing_config_read ON public.billing_config;
CREATE POLICY billing_config_read
ON public.billing_config FOR SELECT
TO authenticated
USING (true);
-- Sin políticas de escritura: solo SECURITY DEFINER / service_role modifican.

-- 4) Historial de pagos ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  currency_code text NOT NULL DEFAULT 'USD',
  billing_cycle text CHECK (billing_cycle IN ('monthly','quarterly','annual')),
  period_start timestamptz,
  period_end timestamptz,
  paid_at timestamptz NOT NULL DEFAULT now(),
  method text,
  reference text,
  status text NOT NULL DEFAULT 'paid' CHECK (status IN ('paid','refunded')),
  request_id uuid REFERENCES public.plan_change_requests(id) ON DELETE SET NULL,
  recorded_by uuid REFERENCES auth.users(id),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payments_business_paid
ON public.payments (business_id, paid_at DESC);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS payments_read ON public.payments;
CREATE POLICY payments_read
ON public.payments FOR SELECT
TO authenticated
USING (
  auth.uid() = business_id
  OR public.is_member_of_team(business_id)
  OR public.is_system_admin()
);
-- Sin INSERT/UPDATE/DELETE para usuarios: solo vía RPC SECURITY DEFINER (admin).

-- 5) Helpers de ciclo/precio -------------------------------------------------
CREATE OR REPLACE FUNCTION public.billing_cycle_months(p_cycle text)
RETURNS integer
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE p_cycle
    WHEN 'monthly' THEN 1
    WHEN 'quarterly' THEN 3
    WHEN 'annual' THEN 12
    ELSE 1
  END;
$$;

CREATE OR REPLACE FUNCTION public.premium_price_for_cycle(p_cycle text)
RETURNS numeric
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
  SELECT COALESCE((SELECT (pricing ->> p_cycle)::numeric FROM public.plans WHERE id = 'premium'), 0);
$$;

-- 6) Estado efectivo de facturación ------------------------------------------
CREATE OR REPLACE FUNCTION public.get_effective_plan_state(target_business_id uuid)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
  sub record;
  v_lead_days integer;
  v_grace_days integer;
  v_state text;
  v_grace_until timestamptz;
  v_days_until_due integer;
  v_now timestamptz := now();
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'No autenticado' USING ERRCODE = 'P0001';
  END IF;

  IF NOT (
    auth.uid() = target_business_id
    OR public.is_member_of_team(target_business_id)
    OR public.is_system_admin()
  ) THEN
    RAISE EXCEPTION 'No autorizado' USING ERRCODE = 'P0001';
  END IF;

  SELECT bc.reminder_lead_days, bc.grace_days INTO v_lead_days, v_grace_days
  FROM public.billing_config bc WHERE bc.id = 1;
  v_lead_days := COALESCE(v_lead_days, 7);
  v_grace_days := COALESCE(v_grace_days, 3);

  SELECT * INTO sub FROM public.subscriptions WHERE user_id = target_business_id LIMIT 1;

  -- Sin suscripción o no premium => free
  IF sub.user_id IS NULL OR sub.plan_id IS DISTINCT FROM 'premium' THEN
    RETURN json_build_object(
      'plan_id', COALESCE(sub.plan_id, 'free'),
      'status', COALESCE(sub.status, 'active'),
      'payment_state', 'free',
      'current_period_end', sub.current_period_end,
      'grace_until', NULL,
      'days_until_due', NULL,
      'billing_cycle', COALESCE(sub.billing_cycle, 'monthly'),
      'lead_days', v_lead_days,
      'grace_days', v_grace_days
    );
  END IF;

  -- Premium
  IF sub.current_period_end IS NULL THEN
    v_state := 'ok';
    v_grace_until := NULL;
    v_days_until_due := NULL;
  ELSE
    v_grace_until := sub.current_period_end + make_interval(days => v_grace_days);
    v_days_until_due := CEIL(EXTRACT(EPOCH FROM (sub.current_period_end - v_now)) / 86400.0)::integer;

    IF v_now <= sub.current_period_end - make_interval(days => v_lead_days) THEN
      v_state := 'ok';
    ELSIF v_now <= sub.current_period_end THEN
      v_state := 'due_soon';
    ELSIF v_now <= v_grace_until THEN
      v_state := 'grace';
    ELSE
      v_state := 'blocked';
    END IF;
  END IF;

  RETURN json_build_object(
    'plan_id', 'premium',
    'status', sub.status,
    'payment_state', v_state,
    'current_period_end', sub.current_period_end,
    'grace_until', v_grace_until,
    'days_until_due', v_days_until_due,
    'billing_cycle', COALESCE(sub.billing_cycle, 'monthly'),
    'lead_days', v_lead_days,
    'grace_days', v_grace_days
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_effective_plan_state(uuid) TO authenticated;

-- 7) Registrar pago (solo admin) ---------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_record_payment(
  p_business_id uuid,
  p_amount numeric,
  p_currency text DEFAULT 'USD',
  p_billing_cycle text DEFAULT NULL,
  p_period_start timestamptz DEFAULT NULL,
  p_period_end timestamptz DEFAULT NULL,
  p_method text DEFAULT NULL,
  p_reference text DEFAULT NULL,
  p_notes text DEFAULT NULL,
  p_request_id uuid DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  admin_email text;
BEGIN
  IF NOT public.is_system_admin() THEN
    RAISE EXCEPTION 'Solo un administrador del sistema puede registrar pagos' USING ERRCODE = 'P0001';
  END IF;
  IF p_business_id IS NULL THEN
    RAISE EXCEPTION 'business_id requerido' USING ERRCODE = 'P0001';
  END IF;
  IF p_amount IS NULL OR p_amount < 0 THEN
    RAISE EXCEPTION 'Monto inválido' USING ERRCODE = 'P0001';
  END IF;
  IF p_billing_cycle IS NOT NULL AND p_billing_cycle NOT IN ('monthly','quarterly','annual') THEN
    RAISE EXCEPTION 'Ciclo de facturación inválido' USING ERRCODE = 'P0001';
  END IF;

  admin_email := public.get_current_user_email();

  INSERT INTO public.payments (
    business_id, amount, currency_code, billing_cycle, period_start, period_end,
    paid_at, method, reference, status, request_id, recorded_by, notes
  )
  VALUES (
    p_business_id, p_amount, COALESCE(NULLIF(trim(p_currency), ''), 'USD'), p_billing_cycle,
    p_period_start, p_period_end, now(), NULLIF(trim(p_method), ''), NULLIF(trim(p_reference), ''),
    'paid', p_request_id, auth.uid(), NULLIF(trim(p_notes), '')
  )
  RETURNING id INTO v_id;

  INSERT INTO public.audit_logs (business_id, actor_id, user_id, user_email, action, resource, details, area)
  VALUES (
    p_business_id, auth.uid(), auth.uid(), admin_email, 'Registrar Pago', 'Pago Premium',
    jsonb_build_object('payment_id', v_id, 'amount', p_amount, 'currency', p_currency,
                       'billing_cycle', p_billing_cycle, 'period_end', p_period_end),
    'Planes'
  );

  RETURN json_build_object('payment_id', v_id, 'business_id', p_business_id, 'amount', p_amount);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_record_payment(uuid, numeric, text, text, timestamptz, timestamptz, text, text, text, uuid) TO authenticated;

-- 8) Extender approve_plan_change_request (DROP+CREATE para evitar overload) --
DROP FUNCTION IF EXISTS public.approve_plan_change_request(uuid, integer, text);

CREATE OR REPLACE FUNCTION public.approve_plan_change_request(
  request_id uuid,
  approved_months integer DEFAULT NULL,
  admin_notes text DEFAULT NULL,
  billing_cycle text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
  req record;
  months integer;
  v_cycle text;
  v_amount numeric;
  v_payment_id bigint;
  period_start timestamptz;
  period_end timestamptz;
  admin_email text;
  v_admin_notes text;
BEGIN
  IF NOT public.is_system_admin() THEN
    RAISE EXCEPTION 'Solo un administrador del sistema puede aprobar solicitudes' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO req FROM public.plan_change_requests WHERE id = request_id FOR UPDATE;
  IF req.id IS NULL THEN
    RAISE EXCEPTION 'Solicitud no encontrada' USING ERRCODE = 'P0001';
  END IF;
  IF req.status <> 'pending' THEN
    RAISE EXCEPTION 'La solicitud ya fue procesada' USING ERRCODE = 'P0001';
  END IF;

  v_cycle := NULLIF(trim(billing_cycle), '');
  IF v_cycle IS NOT NULL AND v_cycle NOT IN ('monthly','quarterly','annual') THEN
    RAISE EXCEPTION 'Ciclo de facturación inválido' USING ERRCODE = 'P0001';
  END IF;

  IF v_cycle IS NOT NULL THEN
    months := public.billing_cycle_months(v_cycle);
  ELSE
    months := COALESCE(approved_months, req.requested_months, 1);
    IF months < 1 THEN months := 1; END IF;
    v_cycle := CASE months WHEN 12 THEN 'annual' WHEN 3 THEN 'quarterly' WHEN 1 THEN 'monthly' ELSE 'monthly' END;
  END IF;

  v_admin_notes := NULLIF(trim(admin_notes), '');
  period_start := now();
  period_end := period_start + make_interval(months => months);
  admin_email := public.get_current_user_email();

  INSERT INTO public.subscriptions (
    user_id, plan_id, status, billing_cycle, current_period_start, current_period_end,
    source, approved_by, approved_at, admin_notes, created_at, updated_at
  )
  VALUES (
    req.business_id, req.requested_plan_id, 'active', v_cycle, period_start, period_end,
    'manual', auth.uid(), now(), v_admin_notes, now(), now()
  )
  ON CONFLICT (user_id) DO UPDATE
  SET plan_id = excluded.plan_id,
      status = excluded.status,
      billing_cycle = excluded.billing_cycle,
      current_period_start = excluded.current_period_start,
      current_period_end = excluded.current_period_end,
      source = excluded.source,
      approved_by = excluded.approved_by,
      approved_at = excluded.approved_at,
      admin_notes = excluded.admin_notes,
      trial_start_at = NULL,
      trial_end_at = NULL,
      cancelled_by = NULL,
      cancelled_at = NULL,
      updated_at = now();

  UPDATE public.plan_change_requests
  SET status = 'approved',
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      admin_notes = v_admin_notes,
      updated_at = now()
  WHERE id = req.id;

  IF req.requested_plan_id = 'premium' THEN
    v_amount := public.premium_price_for_cycle(v_cycle);
    INSERT INTO public.payments (
      business_id, amount, currency_code, billing_cycle, period_start, period_end,
      paid_at, method, reference, status, request_id, recorded_by, notes
    )
    VALUES (
      req.business_id, COALESCE(v_amount, 0), 'USD', v_cycle, period_start, period_end,
      now(), req.payment_method, req.payment_reference, 'paid', req.id, auth.uid(), v_admin_notes
    )
    RETURNING id INTO v_payment_id;
  END IF;

  INSERT INTO public.audit_logs (business_id, actor_id, user_id, user_email, action, resource, details, area)
  VALUES (
    req.business_id, auth.uid(), auth.uid(), admin_email, 'Aprobar Plan', 'Plan Premium',
    jsonb_build_object('request_id', req.id, 'approved_plan', req.requested_plan_id,
                       'approved_months', months, 'billing_cycle', v_cycle,
                       'period_end', period_end, 'payment_id', v_payment_id),
    'Planes'
  );

  RETURN json_build_object(
    'request_id', req.id,
    'business_id', req.business_id,
    'plan_id', req.requested_plan_id,
    'status', 'approved',
    'current_period_end', period_end,
    'billing_cycle', v_cycle,
    'payment_id', v_payment_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.approve_plan_change_request(uuid, integer, text, text) TO authenticated;

-- 9) Extender admin_set_business_plan (DROP+CREATE) --------------------------
DROP FUNCTION IF EXISTS public.admin_set_business_plan(uuid, text, integer, text);

CREATE OR REPLACE FUNCTION public.admin_set_business_plan(
  target_business_id uuid,
  target_plan_id text,
  months integer DEFAULT NULL,
  admin_notes text DEFAULT NULL,
  billing_cycle text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
DECLARE
  m integer;
  v_cycle text;
  v_amount numeric;
  v_payment_id bigint;
  period_start timestamptz;
  period_end timestamptz;
  admin_email text;
  v_admin_notes text;
BEGIN
  IF NOT public.is_system_admin() THEN
    RAISE EXCEPTION 'Solo un administrador del sistema puede cambiar planes' USING ERRCODE = 'P0001';
  END IF;
  IF target_business_id IS NULL THEN
    RAISE EXCEPTION 'business_id requerido' USING ERRCODE = 'P0001';
  END IF;
  IF target_plan_id IS NULL OR target_plan_id NOT IN ('free', 'premium') THEN
    RAISE EXCEPTION 'plan_id inválido' USING ERRCODE = 'P0001';
  END IF;

  v_admin_notes := NULLIF(trim(admin_notes), '');
  admin_email := public.get_current_user_email();

  v_cycle := NULLIF(trim(billing_cycle), '');
  IF v_cycle IS NOT NULL AND v_cycle NOT IN ('monthly','quarterly','annual') THEN
    RAISE EXCEPTION 'Ciclo de facturación inválido' USING ERRCODE = 'P0001';
  END IF;

  IF target_plan_id = 'premium' THEN
    IF v_cycle IS NOT NULL THEN
      m := public.billing_cycle_months(v_cycle);
    ELSE
      m := COALESCE(months, 1);
      IF m < 1 THEN m := 1; END IF;
      v_cycle := CASE m WHEN 12 THEN 'annual' WHEN 3 THEN 'quarterly' WHEN 1 THEN 'monthly' ELSE 'monthly' END;
    END IF;

    period_start := now();
    period_end := period_start + make_interval(months => m);

    INSERT INTO public.subscriptions (
      user_id, plan_id, status, billing_cycle, current_period_start, current_period_end,
      source, approved_by, approved_at, admin_notes, created_at, updated_at
    )
    VALUES (
      target_business_id, 'premium', 'active', v_cycle, period_start, period_end,
      'admin', auth.uid(), now(), v_admin_notes, now(), now()
    )
    ON CONFLICT (user_id) DO UPDATE
    SET plan_id = excluded.plan_id,
        status = excluded.status,
        billing_cycle = excluded.billing_cycle,
        current_period_start = excluded.current_period_start,
        current_period_end = excluded.current_period_end,
        source = excluded.source,
        approved_by = excluded.approved_by,
        approved_at = excluded.approved_at,
        admin_notes = excluded.admin_notes,
        trial_start_at = NULL,
        trial_end_at = NULL,
        cancelled_by = NULL,
        cancelled_at = NULL,
        updated_at = now();

    v_amount := public.premium_price_for_cycle(v_cycle);
    INSERT INTO public.payments (
      business_id, amount, currency_code, billing_cycle, period_start, period_end,
      paid_at, method, reference, status, recorded_by, notes
    )
    VALUES (
      target_business_id, COALESCE(v_amount, 0), 'USD', v_cycle, period_start, period_end,
      now(), 'admin', NULL, 'paid', auth.uid(), v_admin_notes
    )
    RETURNING id INTO v_payment_id;
  ELSE
    INSERT INTO public.subscriptions (
      user_id, plan_id, status, current_period_start, current_period_end,
      source, cancelled_by, cancelled_at, admin_notes, created_at, updated_at
    )
    VALUES (
      target_business_id, 'free', 'cancelled', now(), NULL,
      'admin', auth.uid(), now(), v_admin_notes, now(), now()
    )
    ON CONFLICT (user_id) DO UPDATE
    SET plan_id = excluded.plan_id,
        status = excluded.status,
        current_period_start = excluded.current_period_start,
        current_period_end = excluded.current_period_end,
        source = excluded.source,
        cancelled_by = excluded.cancelled_by,
        cancelled_at = excluded.cancelled_at,
        approved_by = NULL,
        approved_at = NULL,
        admin_notes = excluded.admin_notes,
        trial_start_at = NULL,
        trial_end_at = NULL,
        updated_at = now();
  END IF;

  INSERT INTO public.audit_logs (business_id, actor_id, user_id, user_email, action, resource, details, area)
  VALUES (
    target_business_id, auth.uid(), auth.uid(), admin_email, 'Cambio Manual de Plan', 'Suscripción',
    jsonb_build_object('plan_id', target_plan_id, 'months', months, 'billing_cycle', v_cycle,
                       'current_period_end', period_end, 'payment_id', v_payment_id),
    'Planes'
  );

  RETURN json_build_object(
    'business_id', target_business_id,
    'plan_id', target_plan_id,
    'current_period_end', period_end,
    'billing_cycle', v_cycle,
    'payment_id', v_payment_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_set_business_plan(uuid, text, integer, text, text) TO authenticated;

NOTIFY pgrst, 'reload schema';

-- ============================================================================
-- ROLLBACK (manual):
--   DROP FUNCTION IF EXISTS public.get_effective_plan_state(uuid);
--   DROP FUNCTION IF EXISTS public.admin_record_payment(uuid,numeric,text,text,timestamptz,timestamptz,text,text,text,uuid);
--   DROP FUNCTION IF EXISTS public.premium_price_for_cycle(text);
--   DROP FUNCTION IF EXISTS public.billing_cycle_months(text);
--   DROP TABLE IF EXISTS public.payments;
--   DROP TABLE IF EXISTS public.billing_config;
--   ALTER TABLE public.plans DROP COLUMN IF EXISTS pricing;
--   ALTER TABLE public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_billing_cycle_check;
--   ALTER TABLE public.subscriptions DROP COLUMN IF EXISTS billing_cycle;
--   (y restaurar approve_plan_change_request / admin_set_business_plan a su versión de 3/4 args)
-- ============================================================================
