-- Fase 1 del roadmap contable: Contactos + bases de Cuentas por Cobrar/Pagar.
-- Aplicada a producción el 2026-06-19. Aditiva y segura: tabla nueva + columnas
-- nullable/defaulted. Las transacciones existentes quedan como status='paid'
-- (flujo de caja ya liquidado), sin cambio de comportamiento.
-- Idempotente: usa IF NOT EXISTS y DROP POLICY IF EXISTS para poder re-aplicarse.

create table if not exists public.contacts (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default get_current_business_id() references auth.users(id),
  name        text not null,
  kind        text not null default 'cliente' check (kind in ('cliente','proveedor','ambos')),
  phone       text,
  email       text,
  notes       text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists contacts_user_id_idx on public.contacts(user_id);
create index if not exists contacts_user_name_idx on public.contacts(user_id, name);

alter table public.contacts enable row level security;

-- RLS replicando el patrón del proyecto (reutiliza permisos finanzas.*: las CxC/CxP son financieras).
drop policy if exists contacts_read on public.contacts;
create policy contacts_read on public.contacts
  for select using (has_permission_secure(user_id, 'finanzas.view'));

drop policy if exists contacts_insert on public.contacts;
create policy contacts_insert on public.contacts
  for insert with check ((user_id = get_current_business_id()) and has_permission_secure(user_id, 'finanzas.create'));

drop policy if exists contacts_update on public.contacts;
create policy contacts_update on public.contacts
  for update using (has_permission_secure(user_id, 'finanzas.edit'))
  with check (has_permission_secure(user_id, 'finanzas.edit'));

drop policy if exists contacts_delete on public.contacts;
create policy contacts_delete on public.contacts
  for delete using (has_permission_secure(user_id, 'finanzas.delete'));

-- Bases de CxC/CxP sobre transactions (opcionales, defaults neutros = Cuba "pagado/efectivo").
alter table public.transactions
  add column if not exists contact_id  bigint references public.contacts(id) on delete set null,
  add column if not exists status      text not null default 'paid' check (status in ('paid','pending','partial')),
  add column if not exists due_date    timestamptz,
  add column if not exists paid_amount numeric not null default 0;

create index if not exists transactions_contact_id_idx on public.transactions(contact_id);
create index if not exists transactions_status_idx on public.transactions(user_id, status);
