-- 20260622_s2_account_payments_ledger.sql
-- S2 (Q2) — Libro de abonos para Cuentas por Cobrar/Pagar.
--
-- PROBLEMA: registerPayment guardaba solo un acumulado (`transactions.paid_amount`)
-- con un leer-modificar-escribir desde el cliente -> se pierde el detalle de cada
-- abono (fecha/monto/método) y hay riesgo de lost-update con usuarios concurrentes.
--
-- SOLUCIÓN:
--   1) Tabla `account_payments` = un registro por abono (ledger), ligada a la
--      transacción. (NO se puede llamar `payments`: esa tabla es de la facturación
--      del SaaS/suscripciones.)
--   2) RPC atómica `register_account_payment`: bloquea la cuenta (FOR UPDATE),
--      inserta el abono y recalcula paid_amount = SUM(abonos) + status, todo en una
--      transacción -> sin lost-update ni sobrepago concurrente (estilo S3/Q12).
--   3) `paid_amount` se conserva como CACHÉ (= SUM de abonos), para no romper la
--      vista "Por cobrar/pagar" ni los listados.
--   4) Backfill: por cada transacción con paid_amount>0 se crea UN abono histórico
--      (fechado en la fecha de la transacción) -> SUM(account_payments)=paid_amount
--      desde el día uno.
--
-- Nota de modelo: createTransaction NO se modifica en S2. Las ventas al contado
-- (status 'paid' al crearse) fijan paid_amount=amount sin pasar por el ledger (no
-- son "cuentas" y no aparecen en Por cobrar/pagar). El ciclo de crédito
-- (pending -> abonos -> partial/paid) SÍ pasa siempre por la RPC, donde el historial
-- queda completo. El backfill cubre el histórico ya existente.
--
-- Seguridad: RLS por negocio (permisos finanzas.*, igual que contacts). RPC
-- SECURITY DEFINER + search_path fijo, valida finanzas.edit server-side.
-- Idempotente (IF NOT EXISTS / DROP POLICY IF EXISTS / backfill con NOT EXISTS).
-- Reversible: ver ROLLBACK al final.

create table if not exists public.account_payments (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null default get_current_business_id() references auth.users(id),
  transaction_id    bigint not null references public.transactions(id) on delete cascade,
  amount            numeric not null check (amount > 0),
  paid_at           timestamptz not null default now(),
  method            text,
  note              text,
  fx_units_per_base numeric,  -- tasa al cobrar (base para FX realizada, Q13 stretch)
  created_at        timestamptz not null default now()
);

create index if not exists account_payments_tx_idx on public.account_payments(transaction_id);
create index if not exists account_payments_user_idx on public.account_payments(user_id);

alter table public.account_payments enable row level security;

drop policy if exists account_payments_read on public.account_payments;
create policy account_payments_read on public.account_payments
  for select using (has_permission_secure(user_id, 'finanzas.view'));

drop policy if exists account_payments_insert on public.account_payments;
create policy account_payments_insert on public.account_payments
  for insert with check ((user_id = get_current_business_id()) and has_permission_secure(user_id, 'finanzas.edit'));

drop policy if exists account_payments_update on public.account_payments;
create policy account_payments_update on public.account_payments
  for update using (has_permission_secure(user_id, 'finanzas.edit'))
  with check (has_permission_secure(user_id, 'finanzas.edit'));

drop policy if exists account_payments_delete on public.account_payments;
create policy account_payments_delete on public.account_payments
  for delete using (has_permission_secure(user_id, 'finanzas.delete'));

-- RPC atómica para registrar un abono
create or replace function public.register_account_payment(
  p_transaction_id bigint,
  p_amount numeric,
  p_method text default null,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_business uuid := public.get_current_business_id();
  v_tx public.transactions;
  v_total numeric;
  v_paid numeric;
  v_status text;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'El monto del pago debe ser mayor que cero' using errcode = '22023';
  end if;
  if not public.has_permission_secure(v_business, 'finanzas.edit') then
    raise exception 'No autorizado: requiere permiso finanzas.edit' using errcode = '42501';
  end if;

  -- Bloquea la cuenta del negocio (serializa abonos concurrentes -> sin lost-update).
  select * into v_tx from public.transactions
  where id = p_transaction_id and user_id = v_business
  for update;
  if not found then
    raise exception 'Cuenta no encontrada en el negocio' using errcode = 'P0002';
  end if;

  v_total := v_tx.amount;
  select coalesce(sum(amount), 0) into v_paid
  from public.account_payments where transaction_id = p_transaction_id;

  -- No permitir sobrepago (mantiene el invariante SUM(abonos) = paid_amount <= total).
  if v_paid + p_amount > v_total + 0.005 then
    raise exception 'El abono excede el saldo pendiente' using errcode = '23514';
  end if;

  insert into public.account_payments (user_id, transaction_id, amount, paid_at, method, note)
  values (v_business, p_transaction_id, p_amount, now(), p_method, p_note);

  v_paid := v_paid + p_amount;
  v_status := case when v_paid >= v_total then 'paid' else 'partial' end;

  update public.transactions
  set paid_amount = v_paid, status = v_status
  where id = p_transaction_id and user_id = v_business
  returning * into v_tx;

  return jsonb_build_object(
    'id', v_tx.id,
    'type', v_tx.type,
    'description', v_tx.description,
    'amount', v_tx.amount,
    'paid_amount', v_tx.paid_amount,
    'status', v_tx.status
  );
end;
$$;

revoke all on function public.register_account_payment(bigint, numeric, text, text) from public, anon;
grant execute on function public.register_account_payment(bigint, numeric, text, text) to authenticated;

-- Backfill idempotente: un abono histórico por cada transacción con paid_amount>0.
insert into public.account_payments (user_id, transaction_id, amount, paid_at, method, note)
select t.user_id, t.id, t.paid_amount, coalesce(t.date, now()), 'histórico', 'Abono histórico (migración S2)'
from public.transactions t
where coalesce(t.paid_amount, 0) > 0
  and not exists (select 1 from public.account_payments p where p.transaction_id = t.id);

-- ============================================================================
-- ROLLBACK (manual): el cliente vuelve al leer-modificar-escribir y se elimina el ledger.
--   drop function if exists public.register_account_payment(bigint, numeric, text, text);
--   drop table if exists public.account_payments;  -- (borra el historial de abonos)
-- ============================================================================
